Login/Controllers/InicioController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Login.Models;
using System.Web.Security;
using System.Web.Helpers;
using System.Security.Cryptography;
using System.Text;
using System.IO;

namespace Login.Controllers
{
    public class InicioController : Controller
    {
       

        [HttpGet]
        public ActionResult Login()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Login(LoginViewModel loginDataModel)
        {
            /**********SE INICIA EL WS_Acceso Y SE DECLARA SUS TIPO DE DATOS PARA ENVIAR*********/
            WS_Acceso.WS_Acceso wa = new WS_Acceso.WS_Acceso();
            wa.Timeout = -1;
            WS_Acceso.CABECERA_Type CABECERA = new WS_Acceso.CABECERA_Type();
            WS_Acceso.DATOS_Type DATOS = new WS_Acceso.DATOS_Type();
            CABECERA.APP_CONSUMIDORA = "Login";
            string[] separar = null;
            string dominio = "";
            string passwordEncriptado = "";

            /******SE INICIA EL WS_Acceso Y SE DECLARA SUS TIPO DE DATOS PARA ENVIAR Y RECIBIR*******/
            WS_Acceso.MENSAJERES_Type MENSAJERES = new WS_Acceso.MENSAJERES_Type();
            string ruc = "";
            string codigoParticipante = "";
            string urlEndPoint = "";
            string semilla = "";

            try
            {

                if (ModelState.IsValid)
                {

                    try
                    {

                        /***********************SE ENCRIPTA LA PASSWORD CON SEMILLA********************/
                        semilla = generarKey();
                        if (semilla != "")
                        {
                            passwordEncriptado = Encriptar(semilla, loginDataModel.Password);
                        }
                        else
                        {
                            ViewBag.error = "Password no valido";
                            return View("Login");
                        }

                        separar = loginDataModel.Email.Split('@');
                            dominio = separar[1];
                            DATOS.Dominio = dominio;
                            MENSAJERES = wa.BuscarCliente(CABECERA, DATOS);
                        

                    }
                    catch (Exception ex)
                    {
                        ViewBag.error = "Error de Conexion";
                        return View("Login");
                    }
                    /********ESTA EL CLIENTE EN LA BASE DE DATOS*******/
                    if (MENSAJERES.INTEGRES.DETALLE.DATOS.Cliente_Ruc != "" && MENSAJERES.INTEGRES.DETALLE.DATOS.Cliente_Ruc != null && MENSAJERES.INTEGRES.DETALLE.DATOS.Cliente_Cod_Part != "" && MENSAJERES.INTEGRES.DETALLE.DATOS.Cliente_Cod_Part != null && MENSAJERES.INTEGRES.DETALLE.DATOS.EndPoint_Cli_Cone_xion != "" && MENSAJERES.INTEGRES.DETALLE.DATOS.Cliente_Cod_Part != "" && MENSAJERES.INTEGRES.DETALLE.DATOS.Cliente_Cod_Part != null && MENSAJERES.INTEGRES.DETALLE.DATOS.EndPoint_Cli_Cone_xion != null)
                    {
                        ruc = MENSAJERES.INTEGRES.DETALLE.DATOS.Cliente_Ruc;
                        codigoParticipante = MENSAJERES.INTEGRES.DETALLE.DATOS.Cliente_Cod_Part;
                        urlEndPoint = MENSAJERES.INTEGRES.DETALLE.DATOS.EndPoint_Cli_Cone_xion;
                    }
                    else
                    {
                        ViewBag.error = "Cliente no Encontrado";
                        return View("Login");
                    }


                    /***********************WS_PRODUCTO********************/
                    if (passwordEncriptado != "")
                    {
                        
                            WS_Producto_Dimension.WS_Producto wp = new WS_Producto_Dimension.WS_Producto();
                            wp.Timeout = -1;
                            wp.Url = urlEndPoint;
                            WS_Producto_Dimension.CABECERA_Type CABECERA_Producto = new WS_Producto_Dimension.CABECERA_Type();
                            WS_Producto_Dimension.DATOS_Type DATOS_Producto = new WS_Producto_Dimension.DATOS_Type();

                            /******SE INICIA EL WS_Acceso Y SE DECLARA SUS TIPO DE DATOS PARA ENVIAR Y RECIBIR******/
                            WS_Producto_Dimension.MENSAJERES_Type MENSAJERES_Producto = new WS_Producto_Dimension.MENSAJERES_Type();

                            try
                            {
                                CABECERA_Producto.APP_CONSUMIDORA = "Login";
                                DATOS_Producto.Usuario = loginDataModel.Email;
                                DATOS_Producto.Password = passwordEncriptado;
                                DATOS_Producto.Key = semilla;
                                MENSAJERES_Producto = wp.SolicitarAcceso(CABECERA_Producto, DATOS_Producto);
                            }
                            catch (Exception ex)
                            {
                                ViewBag.error = "Error de Conexion";
                                return View("Login");
                            }

                            /********ESTAN CORRECTAS LAS CREDENCIALES*******/

                            if (MENSAJERES_Producto.INTEGRES.DETALLE.DATOS.resultCode == "1")
                            {
                                Session["username"] = loginDataModel.Email;
                                ViewBag.ruc = ruc;
                                ViewBag.codigoParticipante = codigoParticipante;
                                ViewBag.email = loginDataModel.Email;


                                return View("Index");
                            }
                            else
                            {
                                ViewBag.error = "Usuario o contraseña incorrectos";
                                return View("Login");
                            }
                        
                     
                    }
                    else
                    {
                        ViewBag.error = "Password no valido";
                        return View("Login");
                    }

                    }
                /*********DATOS MAL ESCRITOS, EMAIL O PASSWORD ***********/
                else
                {

                    return View("Login");

                }
            }
            catch (Exception ex)
            {
                ViewBag.error = "Error";
                return View("Login");
            }

            ViewBag.error = "Usuario o contraseña incorrectos";
            return View("Login");

        }

        /******SALIR O CERRAR SESSION*******/
        [HttpGet]
        public ActionResult Logout()
        {
            Session.Remove("username");
            return RedirectToAction("Login");
        }




        /**GENERA UNA KEY DE 32 CARACTERES**/
        public string generarKey()
        {
            var chars = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789";
            var stringChars = new char[32];
            try
            {
                var random = new Random();

                for (int i = 0; i < stringChars.Length; i++)
                {
                    stringChars[i] = chars[random.Next(chars.Length)];
                }

                string finalString = new String(stringChars);
                return finalString;
            }
            catch (Exception ex)
            {
                return "";
            }
        }

        /**ENCRIPTA LA PASSWORD PASANDOLE UNA KEY O SEMILLA**/
        public static string Encriptar(string key, string palabra)
        {
            byte[] iv = new byte[16];
            byte[] array;

            try
            {
                using (Aes aes = Aes.Create())
                {
                    aes.Key = Encoding.UTF8.GetBytes(key);
                    aes.IV = iv;

                    ICryptoTransform encryptor = aes.CreateEncryptor(aes.Key, aes.IV);

                    using (MemoryStream memoryStream = new MemoryStream())
                    {
                        using (CryptoStream cryptoStream = new CryptoStream((Stream)memoryStream, encryptor, CryptoStreamMode.Write))
                        {
                            using (StreamWriter streamWriter = new StreamWriter((Stream)cryptoStream))
                            {
                                streamWriter.Write(palabra);
                            }

                            array = memoryStream.ToArray();
                        }
                    }
                }
            }
            catch (Exception ex)
            {
                return "";
            }

            return Convert.ToBase64String(array);
        }




        /**DESENCRIPTA LA PASSWORD PASANDOLE UNA KEY O SEMILLA, ESTA FUNCION ES LA QUE USA EL WS_Producto**/
        public static string Desencriptar(string key, string palabraEncriptada)
        {
            byte[] iv = new byte[16];
            byte[] buffer = Convert.FromBase64String(palabraEncriptada);

            try
            {
                using (Aes aes = Aes.Create())
                {
                    aes.Key = Encoding.UTF8.GetBytes(key);
                    aes.IV = iv;
                    ICryptoTransform decryptor = aes.CreateDecryptor(aes.Key, aes.IV);

                    using (MemoryStream memoryStream = new MemoryStream(buffer))
                    {
                        using (CryptoStream cryptoStream = new CryptoStream((Stream)memoryStream, decryptor, CryptoStreamMode.Read))
                        {
                            using (StreamReader streamReader = new StreamReader((Stream)cryptoStream))
                            {
                                return streamReader.ReadToEnd();
                            }
                        }

Login/Views/Shared/_Layout.cshtml
<!doctype html>

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Web Cliente</title>
    <!-- Bootstrap -->
    <link href="../Content/css/bootstrap-4.3.1.css" rel="stylesheet">
    <link href="../Content/css/estilos_.css" rel="stylesheet">
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container">
            <a class="navbar-brand" href="#"><img src="../Content/images/logotipo demension_ 1.png"></a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"> <span class="navbar-toggler-icon"></span> </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <form class="form-inline my-2 my-lg-0 ml-auto">
                    <span> <img class="mr-3 d-inline-block" src="../Content/open-iconic-master/svg/person.svg" alt="icon name" style="width:24px;height:24px; "> </span>
                    <!--<button type="button" class="btn btn-primary">Usuario</button>-->
                    <div class="btn-group">
                        <button type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown">
                            @Session["username"]
                        </button>
                        <div class="dropdown-menu">
                            <a class="dropdown-item" href="@Url.Action("Logout", "Inicio")">Salir</a>

                        </div>
                    </div>
            </div>
            </form>
        </div>
        </div>
    </nav>
 
    <div class="container mt-5 border rounded shadow-sm mt-md-5">
        <div class="row  bg-white">

            @RenderBody()
            <section class="col-md-8 bg-white mt-4">
                <div class="connecting-line"></div>
                <ul class="nav nav-tabs flex-nowrap " role="tablist" id="stepProgressBar">
                    <li role="presentation" class="nav-item"> <a href="#" class="nav-link disabled" data-toggle="tab" aria-controls="step1" role="tab" title="paso 1"> 1 </a> </li>
                    <li role="presentation" class="nav-item"> <a href="#" class="nav-link disabled" data-toggle="tab" aria-controls="step2" role="tab" title="paso 2"> 2 </a> </li>
                    <li role="presentation" class="nav-item"> <a href="#" class="nav-link disabled" data-toggle="tab" aria-controls="step3" role="tab" title="paso 3"> 3 </a> </li>
                    <li role="presentation" class="nav-item"> <a href="#" class="nav-link disabled" data-toggle="tab" aria-controls="complete" role="tab" title="paso 4"> 4 </a> </li>
                </ul>
                <form role="form">
                    <!--contenedor1-->
                    <div class="tab-content py-2">
                        <div class="tab-pane active" role="tabpanel" id="step1">


                            <div class="col-md-8 col-lg-12">

                                <img class="img-fluid mb-4" src="../Content/images/82.png">

                                <!--<div class="tab-pane" role="tabpanel" id="complete">
                          <h5></h5>
                        </div>-->
                                <div class="clearfix"></div>
                            </div>
                            <!--fin-contenedor4-->
                </form>
            </section>
        </div>
    </div>
    <footer class="text-center fixed-bottom">
        <div class="container">
            <div class="row">
                <div class="col-12">
                    <p>Copyright © <img src="../Content/images/logo-dimension_p.png" style="width: 10%"></p>
                </div>
            </div>
        </div>
    </footer>

    <!--________________________________________________________________________
        ________________________________________________________________________-->

    <script src="../Scripts/js/jquery-3.3.1.min.js"></script>
    <!-- Include all compiled plugins (below), or include individual files as needed -->
    <script src="../Scripts/js/popper.min.js"></script>
    <script src="../Scripts/js/bootstrap-4.3.1.js"></script>
    <script>
        $(document).ready(function () {
            //Initialize tooltips
            $('.nav-tabs > li a[title]').tooltip();

            //Wizard
            $('a[data-toggle="tab"]').on('show.bs.tab', function (e) {
                var $target = $(e.target);
                if ($target.parent().hasClass('disabled')) {
                    return false;
                }
            });

            $(".next-step").click(function (e) {
                var $active = $('.nav-tabs li>.active');
                $active.parent().next().find('.nav-link').removeClass('disabled');
                nextTab($active);
            });

            $(".prev-step").click(function (e) {
                var $active = $('.nav-tabs li>a.active');
                prevTab($active);
            });
        });

        function nextTab(elem) {
            $(elem).parent().next().find('a[data-toggle="tab"]').click();
        }
        function prevTab(elem) {
            $(elem).parent().prev().find('a[data-toggle="tab"]').click();
        }
    </script>
</body>
</html>